CREATE TABLE plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    url_id varchar(128) NOT NULL UNIQUE,
    name varchar(128) NOT NULL,
    description varchar(1024),

    -- Metadata
    ctime timestamp with time zone NOT NULL
);
CREATE INDEX idx_plan_url_id ON plan USING HASH (url_id);

CREATE TABLE plan_user (
    -- Relations
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    plan_id BIGINT,
    name varchar(128) NOT NULL,
    UNIQUE (plan_id, name),
    FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE CASCADE,

    -- Metadata
    ctime timestamp with time zone NOT NULL
);
CREATE INDEX idx_user_plan_id ON plan_user USING HASH (plan_id);

CREATE TABLE user_date (
    -- Relations
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES plan_user(id) ON DELETE CASCADE,

    -- Data
    date DATE NOT NULL,
    UNIQUE (user_id, date), -- A date can only be picked once per user

    -- Metadata
    ctime timestamp with time zone NOT NULL
);
CREATE INDEX idx_date_user_id ON user_date USING HASH (user_id);