---- Create a new plan

CREATE TABLE plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY
    --urlid varchar(128) NOT NULL UNIQUE,

);

CREATE TABLE plan_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    plan_id BIGINT,
    user_name varchar(128) NOT NULL,
    UNIQUE (plan_id, user_name),
    FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE CASCADE
);

CREATE INDEX idx_plan_id ON plan_user (plan_id);