CREATE TABLE plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    urlid varchar(128) NOT NULL UNIQUE,
    name varchar(128) NOT NULL,

    -- Metadata
    ctime timestamp with time zone NOT NULL
);
CREATE INDEX idx_plan_urlid ON plan USING HASH (urlid);

CREATE TABLE plan_user (
    -- Relations
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    plan_id BIGINT,
    name varchar(128) NOT NULL,
    UNIQUE (plan_id, name),
    FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE CASCADE,

    -- Metadata
    ctime timestamp with time zone NOT NULL
);
CREATE INDEX idx_user_plan_id ON plan_user USING HASH (plan_id);

CREATE TABLE plan_date (
    -- Relations
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id BIGINT,
    plan_id BIGINT,
    FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES plan_user(id) ON DELETE CASCADE,

    -- Data
    date DATE NOT NULL,
    UNIQUE (user_id, plan_id, date),

    -- Metadata
    ctime timestamp with time zone NOT NULL
);
CREATE INDEX idx_plan_date_id ON plan_date USING HASH (plan_id);